name: Dependabot Auto-merge

on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Enable auto-merge for Dependabot PRs
        # Auto-merge only patch and minor updates
        if: ${{ steps.metadata.outputs.update-type == 'version-update:semver-patch' || steps.metadata.outputs.update-type == 'version-update:semver-minor' }}
        run: |
          gh pr merge --auto --squash "$PR_URL"
          gh pr edit "$PR_URL" --add-label "dependencies,safe-update"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Label major updates
        # Label major updates for manual review
        if: ${{ steps.metadata.outputs.update-type == 'version-update:semver-major' }}
        run: |
          gh pr edit "$PR_URL" --add-label "dependencies,major-update,needs-review"
          gh pr comment "$PR_URL" --body "⚠️ **Major version update** - requires manual review and testing before merge."
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Comment on auto-merge
        if: ${{ steps.metadata.outputs.update-type == 'version-update:semver-patch' || steps.metadata.outputs.update-type == 'version-update:semver-minor' }}
        run: |
          gh pr comment "$PR_URL" --body "✅ Auto-merge enabled for ${{ steps.metadata.outputs.update-type }}. Will merge automatically after CI passes."
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
